spring:
  banner:
    location: classpath:banner.txt
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/application
    username: application
    password: application
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Hikari
      auto-commit: false
      maximum-pool-size: 50
server:
  port: 2002

logging:
  level:
    org.hibernate.sql: DEBUG
    com.company.myapplication: DEBUG